import Head from 'next/head'
import useSWR from 'swr'
import type { Product } from '../interfaces';

const fetcher = (url: string) => fetch(url).then((res) => res.json())

import CardComponent from './CardComponent';

export default function Home() {


  const { data, error } = useSWR('/api/products', fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  if (data) {
    console.log(data);
  }

  return (
    <div>
      <Head>
        <title>Dishpatch Frontend Technical Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5 py-10 md:p-12 lg:p-16 bg-oat h-max">
        <div className="prose max-w-5xl mx-auto pl-4">
          <h1 className="text-4xl font-medium">Restaurant Meal Kits</h1>
          <p className='mb-4 max-w-xl'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ac dolor lectus. Etiam sit amet odio dui. Nullam eros sapien, congue a congue id, luctus ac massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae primis in faucibus.</p>
        </div>
        <div className='max-w-5xl mx-auto grid gap-1 lg:grid-cols-3 sm:grid-cols-2 grid-cols-1'>
          {data
            ? data.map((kitProps: Product) => (<CardComponent {...kitProps} />))
            : null}
        </div>
      </main>

    </div>
  )
}
